// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("addlinks")]
    public partial class Addlink
    {
        [Key]
        [Column("id_link")]
        public int IdLink { get; set; }
        [Column("yandex_link")]
        public string YandexLink { get; set; }
        [Column("ga_link")]
        public string GaLink { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.Addlinks))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}