// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("incoming_traffic")]
    public partial class IncomingTraffic
    {
        [Key]
        [Column("id_it")]
        public int IdIt { get; set; }
        [Column("incom_traffic_gv")]
        public int? IncomTrafficGv { get; set; }
        [Column("incom_traffic_mop")]
        public int? IncomTrafficMop { get; set; }
        [Column("new_cards_sold")]
        public int? NewCardsSold { get; set; }
        [Column("op_conversion")]
        public decimal? OpConversion { get; set; }
        [Column("data_month", TypeName = "date")]
        public DateTime? DataMonth { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.IncomingTraffics))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}