// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("inside_club")]
    public partial class InsideClub
    {
        [Key]
        [Column("id_ic")]
        public int IdIc { get; set; }
        [Column("guest_visits")]
        public int? GuestVisits { get; set; }
        [Column("calls_mop_phone")]
        public int? CallsMopPhone { get; set; }
        [Column("calls_recept_phone")]
        public int? CallsReceptPhone { get; set; }
        [Column("calltracking")]
        public int? Calltracking { get; set; }
        [Column("other_leads")]
        public int? OtherLeads { get; set; }
        [Column("data_month", TypeName = "date")]
        public DateTime? DataMonth { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.InsideClubs))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}