// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("key_indicators")]
    public partial class KeyIndicator
    {
        [Key]
        [Column("id_ki")]
        public int IdKi { get; set; }
        [Column("leads_site")]
        public int? LeadsSite { get; set; }
        [Column("new_visitors_site")]
        public int? NewVisitorsSite { get; set; }
        [Column("leads_landing_pages")]
        public int? LeadsLandingPages { get; set; }
        [Column("new_visitors_landing_pages")]
        public int? NewVisitorsLandingPages { get; set; }
        [Column("all_leads_sites")]
        public int? AllLeadsSites { get; set; }
        [Column("goals_advertising")]
        public int? GoalsAdvertising { get; set; }
        [Column("spent_website_promotion")]
        public double? SpentWebsitePromotion { get; set; }
        [Column("cost_lead_sites")]
        public double? CostLeadSites { get; set; }
        [Column("target_cost")]
        public double? TargetCost { get; set; }
        [Column("new_website_visitors")]
        public int? NewWebsiteVisitors { get; set; }
        [Column("mail_subs_shares")]
        public int? MailSubsShares { get; set; }
        [Column("data_month", TypeName = "date")]
        public DateTime? DataMonth { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.KeyIndicators))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}