// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("online_pay")]
    public partial class OnlinePay
    {
        [Key]
        [Column("id_op")]
        public int IdOp { get; set; }
        [Column("pay_site_rub")]
        public double? PaySiteRub { get; set; }
        [Column("pay_site_count")]
        public int? PaySiteCount { get; set; }
        [Column("online_sales")]
        public decimal? OnlineSales { get; set; }
        [Column("average_check")]
        public double? AverageCheck { get; set; }
        [Column("pay_conversion")]
        public decimal? PayConversion { get; set; }
        [Column("data_month", TypeName = "date")]
        public DateTime? DataMonth { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.OnlinePays))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}