// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("setting_table")]
    public partial class SettingTable
    {
        [Key]
        [Column("id_st")]
        public int IdSt { get; set; }
        [Column("incoming_traffics")]
        public bool? IncomingTraffics { get; set; }
        [Column("inside_clubs")]
        public bool? InsideClubs { get; set; }
        [Column("keys_indicators")]
        public bool? KeysIndicators { get; set; }
        [Column("online_pays")]
        public bool? OnlinePays { get; set; }
        [Column("social_mediums")]
        public bool? SocialMediums { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.SettingTables))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}