// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplicationMarketing.Models_
{
    [Table("social_media")]
    public partial class SocialMedium
    {
        [Key]
        [Column("id_sm")]
        public int IdSm { get; set; }
        [Column("leads_vk")]
        public int? LeadsVk { get; set; }
        [Column("other_leads")]
        public int? OtherLeads { get; set; }
        [Column("data_month", TypeName = "date")]
        public DateTime? DataMonth { get; set; }
        public string Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(AspNetUser.SocialMedia))]
        public virtual AspNetUser IdNavigation { get; set; }
    }
}